import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "d-bg": "#080d1a",
        "d-sidebar": "#0a1020",
        "d-card": "#0f1a2e",
        "d-border": "#1a2a4a",
        "d-text": "#e2e8f0",
        "d-muted": "#7a9cc0",
        "d-dim": "#3a5070",
        "d-hover": "#0d1a30",
        "d-user": "#0f1a2e",
        "l-bg": "#ffffff",
        "l-sidebar": "#f0f4ff",
        "l-card": "#f8faff",
        "l-border": "#dbe4ff",
        "l-text": "#0f172a",
        "l-muted": "#475569",
        "l-dim": "#94a3b8",
        "l-hover": "#e8eeff",
        "l-user": "#f0f4ff",
        "accent-DEFAULT": "#3b82f6",
        "accent-hover": "#2563eb",
        "accent-soft": "#eff6ff",
        "accent-text": "#1e40af",
        "danger-DEFAULT": "#ef4444",
        "danger-soft": "#fef2f2",
        "success-DEFAULT": "#10b981",
        "success-soft": "#ecfdf5",
      },
      fontFamily: {
        sans: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      animation: {
        "fade-in": "fadeIn 0.15s ease",
        "slide-up": "slideUp 0.2s ease",
        "blink": "blink 1.2s step-end infinite",
        "pulse-dot": "pulseDot 1.5s ease-in-out infinite",
        "bounce": "bounce 1s infinite",
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: { from: { opacity: "0", transform: "translateY(6px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        blink: { "0%,100%": { opacity: "1" }, "50%": { opacity: "0" } },
        pulseDot: { "0%,100%": { opacity: ".4", transform: "scale(.8)" }, "50%": { opacity: "1", transform: "scale(1.2)" } },
      },
      maxWidth: { chat: "720px" },
    },
  },
  plugins: [],
};
export default config;
